---
version: '3'

services:
  vibinator:
    image: jcostom/vibinator:1.5
    container_name: vibinator
    devices:
      - /dev/gpiomem:/dev/gpiomem
    environment:
      - CHATID=your-chatid-value
      - MYTOKEN=your-token-name
    restart: unless-stopped
    networks:
      - containers

networks:
  containers:
    external: true