---
version: '3'

services:
  vibinator:
    image: jcostom/vibinator:latest
    container_name: vibinator
    devices:
      - /dev/gpiomem:/dev/gpiomem
    environment:
      - USE_TELEGRAM=1
      - TELEGRAM_CHATID=your-chatid-value
      - TELEGRAM_TOKEN=your-token-name
      - TZ=America/New_York
    restart: unless-stopped
    networks:
      - containers

networks:
  containers:
    external: true